#!/bin/bash

ELASTICSTACK_DIRNAME=${PARCEL_DIRNAME:-"ELASTICSTACK-7.8.0"}
export ELASTICSTACK_ES_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/elasticsearch
export ELASTICSTACK_KIBANA_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/kibana
export ELASTICSTACK_LOGSTASH_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/logstash
export ELASTICSTACK_AUDITBEAT_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/auditbeat
export ELASTICSTACK_FILEBEAT_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/filebeat
export ELASTICSTACK_METRICBEAT_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/metricbeat
export ELASTICSTACK_PACKETBEAT_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/packetbeat
