#!/bin/bash

ELASTICSTACK_DIRNAME=${PARCEL_DIRNAME:-"ELASTICSTACK-7.8.0"}
export ES_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/elasticsearch
export KIBANA_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/kibana
export LOGSTASH_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/logstash
export FILEBEAT_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/filebeat
export METRICBEAT_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/metricbeat
export PACKETBEAT_HOME=$PARCELS_ROOT/$ELASTICSTACK_DIRNAME/packetbeat
